apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "app-wildfly.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "app-wildfly.name" . }}
    helm.sh/chart: {{ include "app-wildfly.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "app-wildfly.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "app-wildfly.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: https
              containerPort: 8443
              protocol: TCP
            - name: rfid
              containerPort: 4488
              protocol: TCP
            - name: admin
              containerPort: 9990
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - /opt/jboss/wildfly/bin/jboss-cli.sh --connect --commands=ls | grep 'server-state=running'
              initialDelaySeconds: 30
              timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - /opt/jboss/wildfly/bin/jboss-cli.sh --connect --commands='ls deployment' | grep 'app.war'
              initialDelaySeconds: 5
              timeoutSeconds: 5

          resources:
{{ toYaml .Values.resources | indent 12 }}
      imagePullSecrets:
        - name: regcred
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
