kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "wildfly-mysql.fullname" .}}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
