kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "argus-mysql.fullname" .}}-init-script
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Mi
