apiVersion: v1
kind: Service
metadata:
  name: {{ include "argus-mysql.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "argus-mysql.name" . }}
    helm.sh/chart: {{ include "argus-mysql.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3306
      protocol: TCP
      name: mysql
  selector:
    app.kubernetes.io/name: {{ include "argus-mysql.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    
